---
name: Terraform
on:
  push: null
  branches:
    - main
  paths: "**.tf"
permissions:
  contents: read
jobs:
  terraform: null
  name: Terraform
  runs-on: ubuntu-latest
  defaults: null
  run: null
  shell: bash
